version: 0.2

env:
  variables:
    environment: "prod"
phases:
  install:
    commands:
      - sudo dnf install java-17-amazon-corretto -y
      - |
        sudo wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
        sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
        sudo yum install -y apache-maven
  pre_build:
    on-failure: ABORT
    commands:
      - java -version
      - mvn --version
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - timestamp=$(date '+%Y%m%d_%H%M%S')
      - mv target/helloworld.war target/helloworld_$timestamp.war
      - aws s3 cp target/helloworld_$timestamp.war s3://demo-appplication-artifact-bucket/artifacts/
      - aws ssm put-parameter --name "/application/prod/helloworld" --type "String" --value "helloworld_$timestamp.war" --overwrite
      - ssm_commit_id=$(aws ssm get-parameter --name "/application/prod/latestcommitid")
      - commit_id=$(echo $ssm_commit_id | jq -r '.Parameter.Value')
      - |
        aws codepipeline start-pipeline-execution --name InfrastructurePipeline --source-revisions "{\"actionName\": \"Source\", \"revisionType\": \"COMMIT_ID\", \"revisionValue\": \"${commit_id}\"}"